spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pets?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driverClassName: com.mysql.jdbc.Driver
  #jpa 测试
  jpa:
    hibernate:
      ddl-auto: update # 新增数据库链接必须的参数
    # 控制台显示SQL
    show-sql: true
    properties:
      hibernate.format_sql: true
